In [1]:
import pandas as pd

df = pd.read_csv("トラウト2019レギュラーシーズン　savant_data.csv")

print(df.shape)
print(df.columns.tolist())

(1, 77)
['pitches', 'player_id', 'player_name', 'total_pitches', 'pitch_percent', 'ba', 'iso', 'babip', 'slg', 'woba', 'xwoba', 'xba', 'hits', 'abs', 'launch_speed', 'launch_angle', 'spin_rate', 'velocity', 'effective_speed', 'whiffs', 'swings', 'takes', 'eff_min_vel', 'release_extension', 'pos3_int_start_distance', 'pos4_int_start_distance', 'pos5_int_start_distance', 'pos6_int_start_distance', 'pos7_int_start_distance', 'pos8_int_start_distance', 'pos9_int_start_distance', 'pitcher_run_exp', 'run_exp', 'bat_speed', 'swing_length', 'miss_distance', 'pa', 'bip', 'singles', 'doubles', 'triples', 'hrs', 'so', 'k_percent', 'bb', 'bb_percent', 'api_break_z_with_gravity', 'api_break_z_induced', 'api_break_x_arm', 'api_break_x_batter_in', 'hyper_speed', 'bbdist', 'hardhit_percent', 'barrels_per_bbe_percent', 'barrels_per_pa_percent', 'release_pos_z', 'release_pos_x', 'plate_x', 'plate_z', 'obp', 'barrels_total', 'batter_run_value_per_100', 'xobp', 'xslg', 'pitcher_run_value_per_100', 'xbadiff', 'xobpdiff', 'xslgdiff', 'wobadiff', 'swing_miss_percent', 'arm_angle', 'attack_angle', 'attack_direction', 'swing_path_tilt', 'rate_ideal_attack_angle', 'intercept_ball_minus_batter_pos_x_inches', 'intercept_ball_minus_batter_pos_y_inches']

In [2]:
import pandas as pd

df = pd.read_csv("トラウト2015レギュラーシーズン　savant_data.csv")

print(df.shape)
print(df.columns.tolist())

(1, 77)
['pitches', 'player_id', 'player_name', 'total_pitches', 'pitch_percent', 'ba', 'iso', 'babip', 'slg', 'woba', 'xwoba', 'xba', 'hits', 'abs', 'launch_speed', 'launch_angle', 'spin_rate', 'velocity', 'effective_speed', 'whiffs', 'swings', 'takes', 'eff_min_vel', 'release_extension', 'pos3_int_start_distance', 'pos4_int_start_distance', 'pos5_int_start_distance', 'pos6_int_start_distance', 'pos7_int_start_distance', 'pos8_int_start_distance', 'pos9_int_start_distance', 'pitcher_run_exp', 'run_exp', 'bat_speed', 'swing_length', 'miss_distance', 'pa', 'bip', 'singles', 'doubles', 'triples', 'hrs', 'so', 'k_percent', 'bb', 'bb_percent', 'api_break_z_with_gravity', 'api_break_z_induced', 'api_break_x_arm', 'api_break_x_batter_in', 'hyper_speed', 'bbdist', 'hardhit_percent', 'barrels_per_bbe_percent', 'barrels_per_pa_percent', 'release_pos_z', 'release_pos_x', 'plate_x', 'plate_z', 'obp', 'barrels_total', 'batter_run_value_per_100', 'xobp', 'xslg', 'pitcher_run_value_per_100', 'xbadiff', 'xobpdiff', 'xslgdiff', 'wobadiff', 'swing_miss_percent', 'arm_angle', 'attack_angle', 'attack_direction', 'swing_path_tilt', 'rate_ideal_attack_angle', 'intercept_ball_minus_batter_pos_x_inches', 'intercept_ball_minus_batter_pos_y_inches']

In [3]:
import pandas as pd

df = pd.read_csv("トラウト2022レギュラーシーズン　savant_data.csv")

print(df.shape)
print(df.columns.tolist())

(1, 77)
['pitches', 'player_id', 'player_name', 'total_pitches', 'pitch_percent', 'ba', 'iso', 'babip', 'slg', 'woba', 'xwoba', 'xba', 'hits', 'abs', 'launch_speed', 'launch_angle', 'spin_rate', 'velocity', 'effective_speed', 'whiffs', 'swings', 'takes', 'eff_min_vel', 'release_extension', 'pos3_int_start_distance', 'pos4_int_start_distance', 'pos5_int_start_distance', 'pos6_int_start_distance', 'pos7_int_start_distance', 'pos8_int_start_distance', 'pos9_int_start_distance', 'pitcher_run_exp', 'run_exp', 'bat_speed', 'swing_length', 'miss_distance', 'pa', 'bip', 'singles', 'doubles', 'triples', 'hrs', 'so', 'k_percent', 'bb', 'bb_percent', 'api_break_z_with_gravity', 'api_break_z_induced', 'api_break_x_arm', 'api_break_x_batter_in', 'hyper_speed', 'bbdist', 'hardhit_percent', 'barrels_per_bbe_percent', 'barrels_per_pa_percent', 'release_pos_z', 'release_pos_x', 'plate_x', 'plate_z', 'obp', 'barrels_total', 'batter_run_value_per_100', 'xobp', 'xslg', 'pitcher_run_value_per_100', 'xbadiff', 'xobpdiff', 'xslgdiff', 'wobadiff', 'swing_miss_percent', 'arm_angle', 'attack_angle', 'attack_direction', 'swing_path_tilt', 'rate_ideal_attack_angle', 'intercept_ball_minus_batter_pos_x_inches', 'intercept_ball_minus_batter_pos_y_inches']

In [4]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.13/dist-packages (1.3.2)

In [5]:
import duckdb

con = duckdb.connect()

con.register("statcast", df)

In [6]:
df.head()

,pitches,player_id,player_name,total_pitches,pitch_percent,ba,iso,babip,slg,woba,...,xslgdiff,wobadiff,swing_miss_percent,arm_angle,attack_angle,attack_direction,swing_path_tilt,rate_ideal_attack_angle,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,2105,545361,"Trout, Mike",2130,98.8,0.283,0.347,0.323,0.63,0.418,...,0.026,0.02,30.2,40.3,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_2015 = pd.read_csv("トラウト2015レギュラーシーズン　savant_data.csv")
df_2019 = pd.read_csv("トラウト2019レギュラーシーズン　savant_data.csv")
df_2022 = pd.read_csv("トラウト2022レギュラーシーズン　savant_data.csv")

print("2015:", df_2015.shape)
print("2019:", df_2019.shape)
print("2022:", df_2022.shape)

2015: (1, 77)
2019: (1, 77)
2022: (1, 77)

In [8]:
df = pd.concat(
    [df_2015, df_2019, df_2022],
    ignore_index=True
)

print(df.shape)

(3, 77)

In [9]:
print(df.columns.tolist())

['pitches', 'player_id', 'player_name', 'total_pitches', 'pitch_percent', 'ba', 'iso', 'babip', 'slg', 'woba', 'xwoba', 'xba', 'hits', 'abs', 'launch_speed', 'launch_angle', 'spin_rate', 'velocity', 'effective_speed', 'whiffs', 'swings', 'takes', 'eff_min_vel', 'release_extension', 'pos3_int_start_distance', 'pos4_int_start_distance', 'pos5_int_start_distance', 'pos6_int_start_distance', 'pos7_int_start_distance', 'pos8_int_start_distance', 'pos9_int_start_distance', 'pitcher_run_exp', 'run_exp', 'bat_speed', 'swing_length', 'miss_distance', 'pa', 'bip', 'singles', 'doubles', 'triples', 'hrs', 'so', 'k_percent', 'bb', 'bb_percent', 'api_break_z_with_gravity', 'api_break_z_induced', 'api_break_x_arm', 'api_break_x_batter_in', 'hyper_speed', 'bbdist', 'hardhit_percent', 'barrels_per_bbe_percent', 'barrels_per_pa_percent', 'release_pos_z', 'release_pos_x', 'plate_x', 'plate_z', 'obp', 'barrels_total', 'batter_run_value_per_100', 'xobp', 'xslg', 'pitcher_run_value_per_100', 'xbadiff', 'xobpdiff', 'xslgdiff', 'wobadiff', 'swing_miss_percent', 'arm_angle', 'attack_angle', 'attack_direction', 'swing_path_tilt', 'rate_ideal_attack_angle', 'intercept_ball_minus_batter_pos_x_inches', 'intercept_ball_minus_batter_pos_y_inches']

In [10]:
import sqlite3

# SQLiteデータベースを作成
conn = sqlite3.connect(":memory:")

# DataFrameをSQLのテーブルにする
df.to_sql("trout", conn, index=False, if_exists="replace")

print("SQLテーブル作成完了")

SQLテーブル作成完了

In [11]:
import pandas as pd

# CSVを読み込む
df = pd.read_csv("トラウト2019レギュラーシーズン　savant_data.csv")

# =========================
# ① 行数・列数を確認
# =========================
print("データの行数・列数：", df.shape)

# =========================
# ② 列名をすべて確認
# =========================
print("\n【列名】")
for col in df.columns:
    print(col)

# =========================
# ③ 先頭5行を確認
# =========================
print("\n【先頭5行】")
display(df.head())

データの行数・列数： (1, 77)

【列名】
pitches
player_id
player_name
total_pitches
pitch_percent
ba
iso
babip
slg
woba
xwoba
xba
hits
abs
launch_speed
launch_angle
spin_rate
velocity
effective_speed
whiffs
swings
takes
eff_min_vel
release_extension
pos3_int_start_distance
pos4_int_start_distance
pos5_int_start_distance
pos6_int_start_distance
pos7_int_start_distance
pos8_int_start_distance
pos9_int_start_distance
pitcher_run_exp
run_exp
bat_speed
swing_length
miss_distance
pa
bip
singles
doubles
triples
hrs
so
k_percent
bb
bb_percent
api_break_z_with_gravity
api_break_z_induced
api_break_x_arm
api_break_x_batter_in
hyper_speed
bbdist
hardhit_percent
barrels_per_bbe_percent
barrels_per_pa_percent
release_pos_z
release_pos_x
plate_x
plate_z
obp
barrels_total
batter_run_value_per_100
xobp
xslg
pitcher_run_value_per_100
xbadiff
xobpdiff
xslgdiff
wobadiff
swing_miss_percent
arm_angle
attack_angle
attack_direction
swing_path_tilt
rate_ideal_attack_angle
intercept_ball_minus_batter_pos_x_inches
intercept_ball_minus_batter_pos_y_inches

【先頭5行】

,pitches,player_id,player_name,total_pitches,pitch_percent,ba,iso,babip,slg,woba,...,xslgdiff,wobadiff,swing_miss_percent,arm_angle,attack_angle,attack_direction,swing_path_tilt,rate_ideal_attack_angle,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,2509,545361,"Trout, Mike",2556,98.2,0.291,0.353,0.298,0.645,0.436,...,-0.033,-0.024,19.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
query = """
SELECT
    pa AS "打席数（PA）",
    ba AS "打率（AVG）",
    obp AS "出塁率（OBP）",
    slg AS "長打率（SLG）",
    (obp + slg) AS "OPS",
    hrs AS "本塁打（HR）",
    hits AS "安打（H）",
    bb AS "四球（BB）",
    so AS "三振（SO）"
FROM trout
WHERE pa = 600
"""

result = pd.read_sql_query(query, conn)

# 小数点以下3桁に統一
for col in ["打率（AVG）", "出塁率（OBP）", "長打率（SLG）", "OPS"]:
    result[col] = result[col].map(lambda x: f"{x:.3f}")

# 表を中央揃え＋枠線＋行番号非表示
display(
    result.style
    .hide(axis="index")
    .set_properties(**{
        "text-align": "center",
        "border": "1px solid black",
        "width": "110px"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "110px")
            ]
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "110px")
            ]
        },
        {
            "selector": "table",
            "props": [
                ("border-collapse", "collapse"),
                ("table-layout", "fixed"),
                ("width", "100%")
            ]
        }
    ])
)

In [13]:
query = """
SELECT
    hrs,
    barrels_per_bbe_percent,
    hardhit_percent,
    launch_angle
FROM trout
"""

result_3years = pd.read_sql_query(query, conn)

print(result_3years)

   hrs  barrels_per_bbe_percent  hardhit_percent  launch_angle
0   41                17.692308        52.564103          14.0
1   45                20.872274        48.286604          22.2
2   40                19.666667        51.000000          24.6

In [14]:
years = [2015, 2019, 2022]

hardhit_data = [48.6, 44.4, 51.0]

meatball_data = [7.3, 5.3, 6.7]

comparison = pd.DataFrame({
    "年": [f"{year}年" for year in years],
    "本塁打（HR）": result_3years["hrs"].values,
    "バレル率(Barrel%)": result_3years["barrels_per_bbe_percent"].values,
    "ハードヒット率(Hard-Hit%)": hardhit_data,
    "打球角度(Launch Angle)": result_3years["launch_angle"].values,
    "ミートボール率(Meatball%)": meatball_data
})


# 小数点以下1桁に統一
for col in ["バレル率(Barrel%)", "ハードヒット率(Hard-Hit%)", "打球角度(Launch Angle)", "ミートボール率(Meatball%)"]:
    comparison[col] = comparison[col].map(lambda x: f"{x:.1f}")


# 表を中央揃え＋枠線＋行番号非表示
display(
    comparison.style
    .hide(axis="index")
    .set_properties(**{
        "text-align": "center",
        "border": "1px solid black",
        "width": "110px"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "110px")
            ]
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "110px")
            ]
        },
        {
            "selector": "table",
            "props": [
                ("border-collapse", "collapse"),
                ("table-layout", "fixed"),
                ("width", "100%")
            ]
        }
    ])
)

In [17]:
# =========================
# 球種別HR数を手入力
# =========================

pitch_types = ["Fastball", "Breaking", "Offspeed", "その他"]

hr_2015 = [37, 2, 2, 0]
hr_2019 = [27, 9, 9, 0]
hr_2022 = [24, 11, 4, 1]


# =========================
# 3年分の比較表を作成
# =========================

comparison_hr = pd.DataFrame({
    "球種": pitch_types,
    "2015年": hr_2015,
    "2019年": hr_2019,
    "2022年": hr_2022
})


# =========================
# 表を中央揃え＋枠線＋行番号非表示
# =========================

display(
    comparison_hr.style
    .hide(axis="index")
    .set_properties(**{
        "text-align": "center",
        "border": "1px solid black",
        "width": "110px"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "110px")
            ]
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "110px")
            ]
        },
        {
            "selector": "table",
            "props": [
                ("border-collapse", "collapse"),
                ("table-layout", "fixed"),
                ("width", "100%")
            ]
        }
    ])
)

In [21]:
import pandas as pd

# =========================
# 球種別データ
# =========================

comparison_pitch = pd.DataFrame({
    ("2015", "打率(BA)"): [0.341, 0.204, 0.284],
    ("2015", "期待長打率(xSLG)"): [0.733, 0.306, 0.432],
    ("2015", "空振り率(Whiff%)"): [15.1, 35.2, 37.4],

    ("2019", "打率(BA)"): [0.304, 0.272, 0.304],
    ("2019", "期待長打率(xSLG)"): [0.695, 0.597, 0.775],
    ("2019", "空振り率(Whiff%)"): [15.5, 28.0, 22.1],

    ("2022", "打率(BA)"): [0.285, 0.265, 0.300],
    ("2022", "期待長打率(xSLG)"): [0.600, 0.580, 0.618],
    ("2022", "空振り率(Whiff%)"): [26.7, 38.2, 34.5]
}, index=["Fastball", "Breaking", "Offspeed"])


# =========================
# 列を2段構造にする
# =========================

comparison_pitch.columns = pd.MultiIndex.from_tuples(
    comparison_pitch.columns
)


# =========================
# 数字の表示形式
# =========================

for year in ["2015", "2019", "2022"]:
    comparison_pitch[(year, "打率(BA)")] = comparison_pitch[(year, "打率(BA)")].map(
        lambda x: f"{x:.3f}"
    )

    comparison_pitch[(year, "期待長打率(xSLG)")] = comparison_pitch[(year, "期待長打率(xSLG)")].map(
        lambda x: f"{x:.3f}"
    )

    comparison_pitch[(year, "空振り率(Whiff%)")] = comparison_pitch[(year, "空振り率(Whiff%)")].map(
        lambda x: f"{x:.1f}%"
    )


# =========================
# 表示
# =========================

display(
    comparison_pitch.style
    .set_properties(**{
        "text-align": "center",
        "border": "1px solid black",
        "width": "100px"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "100px")
            ]
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center"),
                ("border", "1px solid black"),
                ("width", "100px")
            ]
        },
        {
            "selector": "table",
            "props": [
                ("border-collapse", "collapse"),
                ("table-layout", "fixed"),
                ("width", "100%")
            ]
        }
    ])
)